# Action Types
ACTION_INSERT = 'INSERT'
ACTION_UPDATE = 'UPDATE'
ACTION_DELETE = 'DELETE'
ACTION_SELECT = 'SELECT'
ACTION_CREATE_TABLE = 'CREATE TABLE'
ACTION_CREATE_DATABASE = 'CREATE DATABASE'

# Database Types
TYPE_MYSQL = 'MYSQL'
TYPE_SQSERV = 'SQLServer'