# Action Types
ACTION_INSERT = 'INSERT'
ACTION_UPDATE = 'UPDATE'
ACTION_DELETE = 'DELETE'
ACTION_SELECT = 'SELECT'
ACTION_CREATE_TABLE = 'CREATE TABLE'
ACTION_CREATE_DB = 'CREATE DATABASE'
ACTION_DROP_DB = 'DROP DATABASE'
ACTION_DROP_TABLE = 'DROP TABLE'

# Database Types
TYPE_MYSQL = 'MYSQL'
TYPE_SQSERV = 'SQLServer'
